const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('public/workouts.js','utf8');
new vm.Script(source);
const statsSource=source.slice(source.indexOf(' function stats('),source.indexOf(' function library('));
const statsContext=vm.createContext({});vm.runInContext(statsSource,statsContext);
assert.match(statsContext.stats({sets:[{reps:12,weightKg:20},{reps:10,weightKg:22},{reps:8,weightKg:24}]}),/652 kg/);
assert.match(statsContext.stats({metrics:{durationSeconds:1800,distanceKm:5}}),/6:00 \/km/);
assert.doesNotMatch(statsContext.stats({metrics:{durationSeconds:1800,distanceKm:null}}),/\/km/);
assert.doesNotMatch(statsContext.stats({metrics:{durationSeconds:1800,distanceKm:0}}),/Infinity|NaN/);
const captureSource=source.slice(source.indexOf(' function capture('),source.indexOf(' const emptySet='));
const weightInput={dataset:{field:'weight'},value:'44.092',defaultValue:'44.092'};
const setRow={dataset:{set:'0'},querySelectorAll:()=>[weightInput]};
const card={dataset:{item:'0'},querySelectorAll:s=>s==='[data-set]'?[setRow]:[]};
const ctx=vm.createContext({draft:{items:[{sets:[{weightKg:20}]}]},root:{querySelectorAll:()=>[card]},$:()=>({value:''}),number:v=>v===''?null:Number(v),unit:()=> 'lb'});
vm.runInContext(captureSource,ctx);
ctx.capture();assert.equal(ctx.draft.items[0].sets[0].weightKg,20,'Merely displaying pounds must not change canonical kg');
weightInput.value='50';ctx.capture();assert.ok(Math.abs(ctx.draft.items[0].sets[0].weightKg-22.6796185)<0.00001,'Edited pounds convert to kg');
weightInput.value='';ctx.capture();assert.equal(ctx.draft.items[0].sets[0].weightKg,null,'Blank load must remain missing');
console.log('PASS: per-set volume, pace, missing/zero distance, lossless unit display, edited pounds, and blank loads.');
